version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.24.0
      - image: rqlite/rqlite:latest
        name: rqlite

    steps:
      # Checkout the code as the first step.
      - checkout
      - run: go version
      - run: test -z "$(gofmt -l . | tee /dev/stderr)"
      - run: go vet ./...
      - run: go test -v ./... -args -host=rqlite
      - run: go test -v -race ./... -args -host=rqlite

workflows:
  test-workflow:
    jobs:
      - test
