version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.22.0

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  test-workflow:
    jobs:
      - test